### ISSUE TITLE
R1 Value Discrepancy

### ISSUE THREAD

**Issue by gentlesartori** [night-howler/protogasm#1]
@night-howler , the schematic (PCB/schematic.png) shows a value of 220K for R1 but the BOM (PCB/BOM.md) says 100K. Which is the correct value?

**Comment by nogasm** [comment]
I haven't built one of these, but 100k is probably fine. It'll reduce the MOSFET turn-off time, which will make it run a little cooler.

**Comment by LanceLake** [comment]
Just to be clear, if I want 15 seconds cooldown, 220k will give me exactly 15 seconds. Right? What do you calculate changing that to 100k would be?

**Comment by night-howler** [comment]
It only affects the slew rate on the MOSFET's gate.  In this application, anything from about 2k to 200k will work fine.  Despite the schematic and BOM, I used a 27k when building mine, probably because I had some laying on the bench when I assembled it.

@LanceLake It won't change the cooldown time.  That's all done in software.  This only affects subtle electrical characteristics which won't change how the device works or what you feel.
